Numpy Array'i Oluşturmak:

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [3]:
a*b

array([ 2,  6, 12, 20])

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
type(a)

numpy.ndarray

In [6]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

In [7]:
np.array([3.14,4,2,13], dtype = "int")

array([ 3,  4,  2, 13])

In [8]:
#Sıfırdan array oluşturma

In [10]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3,5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full((4,4),5)

In [13]:
np.arange(1,31,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [14]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
np.random.normal(10,4,(4,4))

array([[12.73347533,  6.20409956, 11.35294594,  6.3737514 ],
       [13.33247159,  3.49114868,  9.02076751,  9.85828459],
       [12.90879545,  6.88889647, 11.91997696, 18.83662371],
       [10.39723017,  6.20340212,  7.74357608, 18.7920839 ]])

In [17]:
np.random.randint(0,10,(3,3))

array([[3, 5, 9],
       [7, 7, 3],
       [0, 6, 6]])


Özellikleri:

* ndim : boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [2]:
import numpy as np

In [4]:
a = np.random.randint(10, size = 10)

In [5]:
a.ndim

1

In [6]:
a.shape

(10,)

In [7]:
a.size

10

In [8]:
a.dtype

dtype('int32')

In [9]:
b = np.random.randint(10, size = (3,5))

In [10]:
b.ndim

2

In [11]:
b.shape

(3, 5)

In [12]:
b

array([[0, 1, 7, 5, 6],
       [0, 7, 0, 6, 9],
       [5, 4, 2, 4, 5]])

In [13]:
b.size

15

In [14]:
b.dtype

dtype('int32')

Yeniden Şekillendirme (Reshaping)

In [15]:
import numpy as np

In [16]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a.ndim

1

In [20]:
b = a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [22]:
b.ndim

2

Array Birleştirme (Concatenation)

In [23]:
import numpy as np

In [25]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [26]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [27]:
z = np.array([7,8,9,10])

In [28]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# 2 boyutta

In [30]:
a = np.array([[1,2,3],
              [4,5,6]])

In [32]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [33]:
np.concatenate([a,a], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Array Ayırma (Splitting)

In [35]:
import numpy as np

In [36]:
x = np.array([1,2,3,99,99,3,2,1])

In [37]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [38]:
a,b,c = np.split(x, [3,5]) 

In [39]:
a

array([1, 2, 3])

In [40]:
b

array([99, 99])

In [41]:
c

array([3, 2, 1])

In [42]:
# 2 Boyutlu Ayırma

In [43]:
m = np.arange(16).reshape(4,4)

In [44]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [46]:
alt,üst = np.vsplit(m, [2])

In [47]:
alt

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [48]:
üst

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [50]:
sag,sol = np.hsplit(m,[2])

In [51]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [52]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

Array Sıralama (Sorting)

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,3,5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [4]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [5]:
v

array([2, 1, 4, 3, 5])

In [6]:
v.sort()

In [7]:
v

array([1, 2, 3, 4, 5])

In [8]:
# 2 Boyutlu Array Sıralama

In [9]:
m = np.random.normal(20,5,(3,3))
m

array([[25.3677389 , 28.48815233, 15.10460951],
       [24.5534636 , 24.25763512, 18.17754037],
       [12.5275144 , 21.39874364, 26.63337441]])

In [10]:
np.sort(m, axis = 1)

array([[15.10460951, 25.3677389 , 28.48815233],
       [18.17754037, 24.25763512, 24.5534636 ],
       [12.5275144 , 21.39874364, 26.63337441]])

In [12]:
np.sort(m, axis = 0)

array([[12.5275144 , 21.39874364, 15.10460951],
       [24.5534636 , 24.25763512, 18.17754037],
       [25.3677389 , 28.48815233, 26.63337441]])

Fancy İndex ile Elemanlara Erişmek

In [1]:
import numpy as np
v = np.arange(0, 30, 3)

In [2]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [3]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [4]:
al_getir = [1, 3, 5]

In [5]:
v[al_getir] 

array([ 3,  9, 15])

In [6]:
# 2 Boyutta

In [8]:
m = np.arange(9).reshape((3,3))

In [9]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
row = np.array([0,1])
column = np.array([1,2])

In [11]:
m[row, column]

array([1, 5])

Koşullu Eleman İşlemleri

In [12]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [13]:
v < 3

array([ True,  True, False, False, False])

In [14]:
v > 5

array([False, False, False, False, False])

In [15]:
v[v < 3]

array([1, 2])

In [16]:
v[v > 3]

array([4, 5])

In [17]:
v * 2

array([ 2,  4,  6,  8, 10])

In [18]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [19]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)